package blast

const (
	quoteIdentifier              = "\""
	additionIdentifier           = "+"
	subtractionIdentifier        = "-"
	multiplicationIdentifier     = "*"
	divisionIdentifier           = "/"
	ifIdentifier                 = "if"
	spaceIdentifier              = " "
	openParenIdentifier          = "("
	closeParenIdentifier         = ")"
	decimalPointIdentifier       = "."
	assignmentIdentifier         = "="
	equalityIdentifier           = "=="
	lessThanIdentifier           = "<"
	greaterThanIdentifier        = ">"
	lessThanOrEqualIdentifier    = "<="
	greaterThanOrEqualIdentifier = ">="
	trueIdentifier               = "true"
	falseIdentifier              = "false"
	endIdentifier                = "end"
	functionIdentifier           = "function"
	returnIdentifier             = "return"
	commentIdentifier            = "--"
	andIdentifier                = "&&"
)
